import { Glass_Antiqua } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar'
import Footer from './components/Footer'

const inter = Glass_Antiqua({ 
  subsets: ['latin'], 
  weight: ['400']})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  keywords: 'React, Next, JavaScript'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <Navbar />
        <div className='min-h-[70vh]'>

        {children}
        </div>
        <Footer />
        </body>
    </html>
  )
}
